### ISSUE TITLE
Koreksi kehadiran

### ISSUE THREAD

**Issue by dudung** [dudung/nt6094-01-2023-2#6]
+ Tuliskan NIM dan tanggal pertemuan yang ingin dikoreksi kehadirannya.
+ Untuk peserta sit-in tuliskan pula NIM dan tanggal saat telah menghadiri pertemuan kuliah.

**Comment by sabrinaghaida** [comment]
NIM 28723305
sit-in tanggal kehadiran 7 Februari 2024,  21 Februari 2024, 28 Februari 2024

**Comment by ririny** [comment]
NIM 32123003
Ririn Yulianti 
Sit in 21 Februari 2024, 28 Februari 2024
6 Maret 2024 (Ijin ke Lapangan)

**Comment by rezaaryanto** [comment]
NIM 32123007
Reza Aryanto
Sit in tanggal kehadiran 21 Februari 2024, 28 Februari 2024, 6 Maret Hadir tetapi tidak mengisi daftar hadir

**Comment by merrydj** [comment]
NIM 28723304
Merry Dwi Jayanti
Hadir tanggal 21 Februari 2024 tetapi tidak mengisi daftar hadir

**Comment by fhaerannisa** [comment]
NIM 28723301
Frili Haerannisa Kris
Hadir tanggal 21 Februari dan 6 Maret 2024 tetapi tidak mengisi daftar hadir.

**Comment by Fitrayurid** [comment]
NIM 28723001
Fitra Yurid
Hadir tanggal 21 dan 28 februari, tetapi tidak mengisi daftar hadir.

**Comment by syadzaaa** [comment]
NIM 28723007 
Syadza Aisyah Hermadianti
Hadir tanggal 13 Maret 2024, tetapi tidak mengisi daftar hadir.

**Comment by iirrkkhaamm** [comment]
NIM 28723005
Fariz Irkham Muadhif
Hadir tanggal 13 Maret 2024, namun terlewat untuk mengisi daftar hadir.

**Comment by christinpalit** [comment]
NIM 32123008
Christin Palit
13 Maret 2024 (Izin tidak mengikuti kuliah karena sakit - terlampir surat keterangan dokter)
[Surat Keterangan Dokter_Christin Palit.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14650807/Surat.Keterangan.Dokter_Christin.Palit.pdf)

**Comment by RusdiaSugiana** [comment]
NIM 28723003
Rusdia Shaleha Sugiana
Hadir tanggal 20 Maret 2024, Namun terlewat mengisi daftar Hadir

**Comment by sabrinaghaida** [comment]
NIM 28723305
Sabrina Ghaida Fauziyyah 
Hadir tanggal 20 Maret 2024, Namun terlewat mengisi daftar Hadir

**Comment by azicakurnia** [comment]
NIM 28723008
Azica Kurnia Nirwana
Hadir tanggal 20 Maret 2024, Namun terlewat mengisi daftar Hadir

**Comment by iirrkkhaamm** [comment]
NIM 28723005
Fariz Irkham Muadhif
Hadir tanggal 20 Maret 2024, terlewat mengisi daftar Hadir

**Comment by intansalsabila06** [comment]
NIM 28723006
Intan Salsabila Mauludina Sari
Hadir tanggal 20 Maret 2024, terlewat mengisi daftar Hadir

**Comment by syadzaaa** [comment]
NIM 28723007
Syadza Aisyah Hermadianti
Hadir tanggal 20 Maret 2024, terlewat mengisi daftar hadir

**Comment by fhaerannisa** [comment]
NIM 28723301
Frili Haerannisa Kris
Hadir tanggal 20 Maret tetapi terlewat mengisi daftar hadir.

**Comment by RusdiaSugiana** [comment]
NIM 28723003
Rusdia Shaleha Sugiana
Hadir tanggal 3 April 2024, Namun terlewat mengisi daftar Hadir

**Comment by iirrkkhaamm** [comment]
NIM 28723005
Fariz Irkham Muadhif
Hadir tanggal 3 April 2024, terlewat mengisi daftar Hadir
