### ISSUE TITLE
Assignmen 04 -- The use of AI in publications

### ISSUE THREAD

**Issue by dudung** [dudung/nt6094-01-2023-2#7]
+ Create a story on Medium and put link of the story here.
+ Content of the story should cover following ideas at least in 1-2 paragraphs for each ideas:
  - AI definition and types in general,
  - the use of AI in some fields,
  - the use of AI in scientific publications,
  - ethics and rule in using AI in publications,
  - AI-based systems and platforms for publications,
  - latest hot issues about AI-assisted publications that is circulating in social media currently,
  - illustration how to use AI in creating introduction part of a scientific paper.
+ This task is performed during the session 0900-1100.

**Comment by dindactr** [comment]
Dear Sir, here I attached the medium link to the 4th assignment.

https://medium.com/@dindacitrautami99/assignmen-04-the-use-of-ai-in-publications-7-b72c13e48c5e

Best Regards,
Dinda Citra Utami (20923006)

**Comment by kwarsanaut** [comment]
Dear Sir, here I attached the medium link to the 4th assignment.

https://medium.com/@kwarsarajab/title-revolutionizing-scientific-publishing-with-artificial-intelligence-pioneering-research-579bcfda6fff

Best Regards,
Kwarsa Rajab Matalapu

**Comment by nuralifiah** [comment]
Dear Sir, here I attached the medium link to the 4th assignment.

https://medium.com/@nuralifiah/assignmen-04-the-use-of-ai-in-publications-a1c4251f6ad5

Best Regards,
Nur Alifiah (20923007)

**Comment by petalflows** [comment]
Dear Sir, here I attached the medium link to the 4th assignment.

https://medium.com/@bungarnfss/the-use-of-ai-in-publications-c8c1d780f038

Best Regards,
Siti Bunga Rohiyatun Nufus (20923010)

**Comment by rikepradila** [comment]
Dear Sir, here I attached the medium link to the 4th assignment.

https://medium.com/@rikepradila/artificial-intelligence-1b7730a08f47

Best Regards,
Rike Pradila (20923012)

**Comment by zahraakbari24** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si., here I am sending you the link to this assignment: 

https://medium.com/@zahraakbari24/the-use-of-ai-in-publications-745118c40b20

Best regards,
Zahra Akbari Ariadji (30618001)

**Comment by azicakurnia** [comment]
Dear Sir, hear I attached the medium story link for my 4th assignment.

https://medium.com/@azica.kurnia/the-use-of-artificial-intelligence-ai-in-publication-6d7e70483333
Azica Kurnia Nirwana (28723008)

Thank you.

**Comment by rizalmuhammadramdhan** [comment]
Dear Sir, here I attached the medium story link for my 4th assignment
https://medium.com/@rizalmuhammadramdhan12/artificial-intelligent-for-publications-6cd207bd9474

Thank you sir

**Comment by rezaaryanto** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si , 
here I attached the medium story link for my 4th assignment
https://medium.com/@rezaaryanto01/assignmen-04-the-use-of-ai-in-publications-7-cbfa7d8f810b

Reza Aryanto (32123007)
Thank you Sir

**Comment by merrydj** [comment]
Dear Sir,
Here I attached the medium link to 4th assignment about using AI in publication.
https://medium.com/@merry.dije/the-use-of-ai-in-publication-d0a4f9bcd4b2

Thank you,
Best Regards,
Merry

**Comment by ririny** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si ,
Here I attached the medium link to 4th assignment about using AI in publication.
https://medium.com/@ririnyuliantii/assignment-4-the-use-of-ai-in-publications-a5ddda954f43

Thank you
Best Regards,
Ririn Yulianti

**Comment by intansalsabila06** [comment]
Good Morning Sir.
I have finished the fourth assignment with the topics of the use of AI publications
https://medium.com/@intansalsabila0601/on-defining-artificial-intelligence-d20d2b46608f

Best regard
Intan Salsabila (28723006)

**Comment by iirrkkhaamm** [comment]
I have attached my assignment below, thank you

https://medium.com/@irkhammm24/ai-definition-and-types-in-general-775ad8831fd6

**Comment by syadzaaa** [comment]
Dear Sir, here I attached the medium link to the 4th assignment.

https://medium.com/@syadza/assignmen-04-the-use-of-ai-in-publications-ff632dae1636

Best Regards, 
Syadza Aisyah Hermadianti (28723007)

**Comment by fhaerannisa** [comment]
Dear Sir,

Here, I have attached the link to the 4th assignment about the use of AI in publications.
https://medium.com/@fhaerannisa/the-use-of-ai-in-publications-23c14c961ccc

Thank you.
Frili Haerannisa Kris (28723301)

**Comment by sabrinaghaida** [comment]
Dear Sir,

I have finished the fourth assignment with the topics of the use of AI publications
https://medium.com/@sabrinaghaida/ai-in-scientific-journals-good-or-bad-daa20af2368e

Best regard
Sabrina Ghaida
28723305

**Comment by arisulistyowati** [comment]
Here I attach my task about the story of Artificial Intelligence (AI)

https://medium.com/@arisulistyowati/all-about-artificial-intelligence-ai-5b0f1786a8d0

Best Regards,
Ari Sulistyowati (20922008)

**Comment by ayuhanifah** [comment]
Dear Dr.rer.nat.Sparisoma Viridi,

Here I attached my assignment's answer about AI in medium link,

https://medium.com/@ayuhnfh00/ai-for-scientific-writing-9a60692a48b4

Thank you for your assistance

Sincerely,
Ayu Hanifah

**Comment by ipwardhani** [comment]
Dear Sir,
Here I attached the story link for my 4th assignment: 

https://ipwardhani.medium.com/assignment-04-the-use-of-artificial-intelligence-in-scientific-publications-781f1fe27a27

Thank you.
Sincerely,
Issana P. Wardhani (20923002)

**Comment by christinpalit** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si.

Here I attached the medium link to 4th Assignment, Sir.

https://christinpalit.medium.com/the-use-of-ai-in-publications-e5f585be8aa4  

Thankyou.
Sincerely,
Christin Palit (32123008)

**Comment by Fitrayurid** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si.

Here I attached the medium link for my 4th assignment.

https://medium.com/@fyurid/the-role-of-ai-is-it-fair-to-use-ai-platforms-for-scientific-publication-3c6ea7a2d6ea

Thank you.
Sincerely,
Fitra (28723001)

**Comment by RusdiaSugiana** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si.

I have attached my assignment below, thank you

https://medium.com/@rusdiasugiana/artificial-intelligence-ai-refers-to-the-development-of-computer-systems-that-can-simulate-human-1b88f74a2275

**Comment by riskaviana20** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si.

I have attached the medium link for my 4th assignment.
https://medium.com/@riskaviana.k/assignment-4-the-use-of-ai-in-publications-d96787cc3002

Thank you.
Riskaviana (32123005)

**Comment by nisaamandar** [comment]
Good morning, sir.
With humility, I apologize for being late in submitting assignments for last week's. So, here is my article https://medium.com/@nisamanda13/artificial-intelligence-in-publications-62a06d007011
Thank you in advance.

Nisa Amanda Rachmadani (28722301)

**Comment by agnesindrwt** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si.,

I apologize for the late assignment due to my schedule here for a double degree program, there is some info that I skipped including this task. Thank you in advance.

https://medium.com/@agnesindrwt/assignment-4-the-use-of-ai-in-publication-b8348d579e84
