### ISSUE TITLE
Midterm -- 03 Apr 2024

### ISSUE THREAD

**Issue by dudung** [dudung/nt6094-01-2023-2#9]
+ Read the problems [NT6094-01-2023-02_UTS_03Apr2024_0900_v1.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14844242/NT6094-01-2023-02_UTS_03Apr2024_0900_v1.pdf)
+ Upload your answer in PDF format here with filename format as instructed.
+ Notice the deadline.

**Comment by dindactr** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si., here I attached the results of the midterm exam answers below

[UTS_Dinda Citra Utami (20923006).pdf](https://github.com/dudung/nt6094-01-2023-2/files/14852081/UTS_Dinda.Citra.Utami.20923006.pdf)

Best Regards

Dinda Citra Utami (20923006)

**Comment by ririny** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.

Below I have attached the UTS that I have worked on.
[32123003 (Ririn Yulianti).pdf](https://github.com/dudung/nt6094-01-2023-2/files/14861314/32123003.Ririn.Yulianti.pdf)

For your attention, I say thank you

Regards
Ririn Yulianti

**Comment by ayuhanifah** [comment]
Dear Dr.rer.nat.Sparisoma Viridi,

Here I attached my midterm's answer in pdf format,

[28723002.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14862724/28723002.pdf)

Thank you for your assistance

Sincerely,
Ayu Hanifah

**Comment by petalflows** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.

Below I have attached my midterm's answer in pdf format.

[20923010.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14871471/20923010.pdf)

Thank you for your attention, 

Best Regards,

Siti Bunga Rohiyatun Nufus (20923010)

**Comment by kwarsarajab** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.

Below I have attached my midterm's answer in pdf format.
[20923008.pdf.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14871503/20923008.pdf.pdf)

Thank you for your assistance

Best Regards,,
Kwarsa rajab

**Comment by agnesindrwt** [comment]
Dear Sir,

Here I attach the document of my midterm answer. Thank you.

Best Regards,
Agnes Indarwati Susanto (20923013)

[20923013.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14871530/20923013.pdf)

**Comment by kwarsanaut** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.

Below I have attached my midterm's answer in pdf format.

[20923008.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14871556/20923008.pdf)

Thank you for your attention

Best Regards,
Kwarsa rajab

**Comment by merrydj** [comment]
Dear Sir,
Here I attached the midterm task.

[28723304.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14872222/28723304.pdf)

thank you

Best Regards,
Merry

**Comment by nisaamandar** [comment]
Dear, sir.
File below is the assignment I have completed. Thank you in advance.

[28722301.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14873590/28722301.pdf)

Best regard,
Nisa Amanda Rachmadani.

**Comment by iirrkkhaamm** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.
Here I attach the answers from mid-semester exams for this course 

[28723005.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14874339/28723005.pdf)

thank you sir.

Best Regards,
Fariz Irkham Muadhif

**Comment by nuralifiah** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.

Below I have attached the UTS that I have worked on.
[20923007.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14874399/20923007.pdf)

For your attention, I say thank you

Regards
Nur Alifiah

**Comment by intansalsabila06** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.
Here I attach the answers from mid-semester exams for this course

[Intan Salsabila_28723006_UTS TPJI.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14874425/Intan.Salsabila_28723006_UTS.TPJI.pdf)


thank you sir.

Best Regards,
Intan Salsabila

**Comment by syadzaaa** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si., 
Here I attached the results of the midterm exam answers below

[Uploading 28723007.pdf…]()

Thank you sir. 

Best Regards, 
Syadza Aisyah Hermadianti 
28723007

**Comment by rikepradila** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.

Here I attach the document of my midterm answer.
[20923012.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14876111/20923012.pdf)

Thank you sir.

Best Regards,
Rike Pradila
20923012

**Comment by azicakurnia** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.

Here I attach the document of my midterm test answer
[28723008.pdf]

Thank you, Sir.

Best Regards,
Azica Kurnia Nirwana

**Comment by azicakurnia** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.

Here I attach the document of my midterm test answer
[28723008.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14876656/28723008.pdf)

Thank you, Sir.

Best Regards,
Azica Kurnia Nirwana

**Comment by syadzaaa** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si., Here I attached the results of the midterm exam answers below

[28723007.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14877513/28723007.pdf)
 
Thank you sir.
 
Best Regards, 
Syadza Aisyah Hermadianti 
28723007

**Comment by ipwardhani** [comment]
Dear Sir,
Here I attached the results of the midterm exam answers for this course.

[20923002.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14877710/20923002.pdf)

Thank you.
Sincerely,
Issana P. Wardhani
20923002

**Comment by Fitrayurid** [comment]
Dear Sir,

Here I attach the document of my midterm answer. Thank you.
[28723001.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14878131/28723001.pdf)

Best Regards,
Fitra Yurid (28723001)

**Comment by fhaerannisa** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si.,

Attached is my answer for the midterm exam.
[28723301.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14878225/28723301.pdf)

Thank you.
Sincerely,
Frili Haerannisa Kris (28723301)

**Comment by riskaviana20** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.
Here I attach the answers of mid-semester exams
[32123005.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14878517/32123005.pdf)


Thank you
Riskaviana Kurniawati
32123005

**Comment by rizalmuhammadramdhan** [comment]
Dear Dr. rer. nat. Sparisoma Viridi, S.Si.,

Attached is my answer for the midterm exam.
[28723302.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14878714/28723302.pdf)

Thank you.
Sincerely,
Rizal Muhammad Ramdhan (28723302)

**Comment by RusdiaSugiana** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.
Here I attach the answers from mid-semester exams for this course

[28723003.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14878898/28723003.pdf)

Best Regards,
Rusdia Shaleha Sugiana (28723003)

**Comment by sabrinaghaida** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.
Here I attach the answers from midterm exams for this course. I apologize for the delay in submitting my midterm task. Unfortunately, I was unable to complete it on time. However, I am committed to submitting it as soon as possible.

[28723305.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14879399/28723305.pdf)

Best Regards,
Sabrina Ghaida Fauziyyah (28723305)

**Comment by zahraakbari24** [comment]
[30618001.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14891292/30618001.pdf)

Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.,

I apologize I uploaded the file on this github issue at 8am yesterday (5 April 2024), but for some reason it's not showing up here. Here I resubmit my midterm (UTS) file.

Best regards,
Zahra Akbari A (30618001)

**Comment by rezaaryanto** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si

[32123007.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14891954/32123007.pdf)

Please allow me, previously I uploaded my midterm on Friday (5 April 2024) at 02.00 am at the following link
https://github.com/dudung/nt8098-01-2023-2/issues/1

This morning I was notified by a PhD student who also uploaded on the link above, to re-upload on this link.
https://github.com/dudung/nt6094-01-2023-2/issues/9
Here i resubmit my Midterm (UTS) File. I apologize for it Sir.

Best regards
Reza Aryanto (32123007)

**Comment by christinpalit** [comment]
Dear Dr. rer. Nat. Sparisoma Viridi, S.Si.

Here I attach the answers of mid-semester exams. My apologize for late in submitting my mid exams document.


[32123008.pdf](https://github.com/dudung/nt6094-01-2023-2/files/14913233/32123008.pdf)

Thank you
Christin Palit
32123008
